repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-xml
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.9.6
  hooks:
    - id: pylint
      args:
        - --rcfile=.pylintrc
        - --exit-zero

- repo: https://github.com/psf/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args:
        - --config=.flake8
        - --extend-exclude=venv

- repo: https://github.com/DmytroLitvinov/pep8-naming
  rev: 1.6.0
  hooks:
    - id: pep8-naming
      args:
        - --config=.pep8-naming

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      args:
        - --config-file=.mypy.ini
